spring.application.name=application

spring.datasource.url=jdbc:mariadb://localhost:3306/KRS
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

server.port=8090

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

jwt.secret=krs-accounting-secret-key-must-be-at-least-256-bits-long-for-hs256
jwt.expiration=86400000

logging.level.org.hibernate.tool.schema=DEBUG
logging.level.org.springframework.security=INFO
