services:
  mariadb:
    image: mariadb:11
    container_name: mariadb_local
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: KRS
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
          test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost" ]
          interval: 10s
          timeout: 5s
          retries: 5

volumes:
  mariadb_data:

app:
    build: .
    networks:
      - backend

networks:
  backend: